#
# Module manifest for module 'Psfah'
#
# Generated by: Jess Pomfret
#
# Generated on: 09/05/2020
#
@{

    # Script module or binary module file associated with this manifest.
    RootModule             = 'PSFah.psm1'

    # Version number of this module.
    ModuleVersion          = '0.0.1'

    # ID used to uniquely identify this module
    GUID                   = '44b4ba34-1e2b-4648-bce4-6ab6262318f8'

    # Author of this module
    Author                 = 'Jess Pomfret'

    # Copyright statement for this module
    Copyright              = '(c) 2020. All rights reserved.'

    # Description of the functionality provided by this module
    Description            = 'Control functions for the Folding at Home Client'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion      = '5.1'

    # Name of the Windows PowerShell host required by this module
    PowerShellHostName     = ''

    # Minimum version of the Windows PowerShell host required by this module
    PowerShellHostVersion  = ''

    # Minimum version of the .NET Framework required by this module
    DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module
    CLRVersion             = ''

    # Processor architecture (None, X86, Amd64, IA64) required by this module
    ProcessorArchitecture  = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules        = @()

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies     = @()

    # Script files () that are run in the caller's environment prior to importing this module
    ScriptsToProcess       = @()

    # Type files (xml) to be loaded when importing this module
    TypesToProcess         = @()

    # Modules to import as nested modules of the module specified in ModuleToProcess
    NestedModules          = @()

    # Functions to export from this module
    FunctionsToExport      = @(
        'Set-FahStatus'
    )

    # Cmdlets to export from this module
    CmdletsToExport        = @()

    # Variables to export from this module
    VariablesToExport      = @()

    # Aliases to export from this module
    AliasesToExport        = @()

    # List of all modules packaged with this module
    ModuleList             = @()

    # List of all files packaged with this module
    FileList               = ''

    PrivateData            = @{}
}
